PlatformBundle\Entity\Usuario:
    type: entity
    table: Usuarios
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombreCompleto:
           type: string
           length: 255
       
    lifecycleCallbacks: {  }
